"""Deterministic counterexample search, without a model and without luck.

Given a seed corpus and a way to compare one input on both systems, look
for an input on which they disagree. Two sources of candidates, in a fixed
order: the boundary values of every leaf in every seed (neighbours,
extremes, null, empty, missing), then random mutations drawn from a
catalogue with a PRNG whose seed is part of the result. The same seed and
the same corpus produce the same sequence of inputs, which is what lets a
search be replayed from its record.

When a divergence is found it is shrunk: a greedy, restart-on-success
reduction that keeps only candidates the comparator still rejects, so the
minimized input reproduces the divergence by construction. Both the first
failing input and the minimized one are kept.

A search that finds nothing says :data:`~invara.assurance.claims.NO_DIVERGENCE_FOUND`.
It is not allowed to say anything stronger.
"""

from __future__ import annotations

import json
import math
import time
from dataclasses import dataclass
from typing import Any, Callable, Iterator, Sequence

from .claims import DIVERGED, NO_DIVERGENCE_FOUND, UNVERIFIABLE
from .manifest import CorpusItem, content_digest

__all__ = ["Prng", "SearchResult", "boundary_candidates", "mutate", "search", "shrink"]

_MASK = (1 << 64) - 1
_INT_MIN, _INT_MAX = -(2**63), 2**63 - 1
_UNICODE = ("한글", "🙂", "\x00", "é", "‮RTL", "ﬁ", " \t\n", "Ω≈ç√", "日本語", "🇰🇷")

Path = tuple[Any, ...]


class Prng:
    """splitmix64 — small, well distributed, and identical on every platform.

    Written out rather than taken from :mod:`random` so the sequence a
    search record names can be regenerated by any future interpreter
    without trusting a library's algorithm to stay put.
    """

    def __init__(self, seed: int) -> None:
        self.state = int(seed) & _MASK

    def next_u64(self) -> int:
        self.state = (self.state + 0x9E3779B97F4A7C15) & _MASK
        z = self.state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & _MASK
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & _MASK
        return z ^ (z >> 31)

    def randint(self, low: int, high: int) -> int:
        return low + self.next_u64() % (high - low + 1)

    def choice(self, sequence: Sequence[Any]) -> Any:
        return sequence[self.randint(0, len(sequence) - 1)]

    def random(self) -> float:
        return (self.next_u64() >> 11) / float(1 << 53)


# --------------------------------------------------------------------------
# tree helpers


from .normalize import _is_number  # noqa: E402 - one definition of "a number" for the whole package


def _sites(value: Any, path: Path = ()) -> list[tuple[Path, Any]]:
    out: list[tuple[Path, Any]] = [(path, value)]
    if isinstance(value, dict):
        for key in sorted(value, key=str):
            out.extend(_sites(value[key], (*path, key)))
    elif isinstance(value, list):
        for index, item in enumerate(value):
            out.extend(_sites(item, (*path, index)))
    return out


def _copy(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _copy(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_copy(item) for item in value]
    return value


def _set(value: Any, path: Path, new: Any) -> Any:
    if not path:
        return _copy(new)
    head, rest = path[0], path[1:]
    if isinstance(value, dict):
        out = {key: (_set(item, rest, new) if key == head else _copy(item)) for key, item in value.items()}
        return out
    if isinstance(value, list):
        return [_set(item, rest, new) if index == head else _copy(item) for index, item in enumerate(value)]
    return _copy(value)


def _delete(value: Any, path: Path) -> Any:
    head, rest = path[0], path[1:]
    if isinstance(value, dict):
        if rest:
            return {key: (_delete(item, rest) if key == head else _copy(item)) for key, item in value.items()}
        return {key: _copy(item) for key, item in value.items() if key != head}
    if isinstance(value, list):
        if rest:
            return [_delete(item, rest) if index == head else _copy(item) for index, item in enumerate(value)]
        return [_copy(item) for index, item in enumerate(value) if index != head]
    return _copy(value)


def _text(path: Path) -> str:
    return "/" + "/".join(str(part) for part in path)


def _size(value: Any) -> int:
    return len(json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":"), default=str))


# --------------------------------------------------------------------------
# boundary values


#: Boundary tiers, cheapest bug-finders first: the neighbours of every
#: number, then zero and the sign, then the extremes, then null / empty /
#: missing. The search interleaves tiers across seeds, so the first runs
#: cover the neighbourhood of every recorded input before any extreme.
_TIERS = 4


def _numeric_tiers(value: Any) -> list[list[Any]]:
    if isinstance(value, float):
        tiers = [[value - 1, value + 1, value + 1e-9, value - 1e-9], [0.0, 1.0, -1.0, -value, 0.5], [value * 2, 1e308, -1e308, 5e-324]]
    else:
        tiers = [[value - 1, value + 1], [0, 1, -1, -value], [value * 2, 2**31 - 1, 2**31, 2**63 - 1, -(2**63)]]
    seen: list[Any] = [value]
    out: list[list[Any]] = []
    for tier in tiers:
        kept: list[Any] = []
        for candidate in tier:
            if candidate not in seen:
                seen.append(candidate)
                kept.append(candidate)
        out.append(kept)
    return out


def _tier_candidates(value: Any, tier: int) -> Iterator[tuple[Any, str]]:
    """The boundary candidates of one tier, built one at a time in a fixed site order.

    Each candidate is a copy of the input; building them lazily keeps one
    candidate alive at a time instead of every candidate of every seed
    (sites squared per seed) before the first mutated run starts.
    """

    for path, node in _sites(value):
        where = _text(path)
        if _is_number(node):
            numeric = _numeric_tiers(node)
            if tier < len(numeric):
                for boundary in numeric[tier]:
                    yield _set(value, path, boundary), f"numeric-boundary:{where}={boundary!r}"
        if tier != _TIERS - 1:
            continue
        if node is not None:
            yield _set(value, path, None), f"null:{where}"
        if isinstance(node, str) and node != "":
            yield _set(value, path, ""), f"empty:{where}"
        elif isinstance(node, list) and node:
            yield _set(value, path, []), f"empty:{where}"
        elif isinstance(node, dict) and node:
            yield _set(value, path, {}), f"empty:{where}"
        if path:
            yield _delete(value, path), f"missing:{where}"


def tiered_boundary_candidates(value: Any) -> list[list[tuple[Any, str]]]:
    """Boundary candidates grouped by tier, each tier in a fixed site order (materialised; the search uses the lazy form)."""

    return [list(_tier_candidates(value, tier)) for tier in range(_TIERS)]


def boundary_candidates(value: Any) -> Iterator[tuple[Any, str]]:
    """Every leaf pushed to its edges, in a fixed order, one at a time. Deterministic by construction."""

    for tier in range(_TIERS):
        yield from _tier_candidates(value, tier)


# --------------------------------------------------------------------------
# random mutations


def _mutations_for(node: Any, path: Path, prng: Prng) -> list[tuple[str, Callable[[], Any]]]:
    where = _text(path)
    options: list[tuple[str, Callable[[], Any]]] = [(f"null:{where}", lambda: None)]
    if _is_number(node):
        step = prng.choice([1, -1, 2, -2, 10, -10]) if isinstance(node, int) else prng.choice([1e-9, -1e-9, 0.5, -0.5, 1.0, -1.0])
        options += [
            (f"numeric-zero:{where}", lambda: 0 if isinstance(node, int) else 0.0),
            (f"numeric-sign:{where}", lambda: -node),
            (f"numeric-min:{where}", lambda: _INT_MIN if isinstance(node, int) else -1e308),
            (f"numeric-max:{where}", lambda: _INT_MAX if isinstance(node, int) else 1e308),
            (f"numeric-step:{where}={step!r}", lambda: node + step),
            (f"numeric-type:{where}", lambda: float(node) if isinstance(node, int) else int(node) if abs(node) < 2**53 else 0),
        ]
    elif isinstance(node, str):
        fragment = prng.choice(_UNICODE)
        factor = prng.choice([0, 2, 50, 1000])
        options += [
            (f"empty:{where}", lambda: ""),
            (f"string-length:{where}x{factor}", lambda: (node or "x") * factor),
            (f"string-unicode:{where}+{fragment!r}", lambda: node + fragment),
            (f"string-unicode:{where}={fragment!r}", lambda: fragment),
            (f"string-numeric:{where}", lambda: "0"),
            (f"string-whitespace:{where}", lambda: " " + node + " "),
        ]
    elif isinstance(node, bool):
        options.append((f"bool-flip:{where}", lambda: not node))
    elif isinstance(node, list):
        options.append((f"empty:{where}", lambda: []))
        if node:
            index = prng.randint(0, len(node) - 1)
            other = prng.randint(0, len(node) - 1)
            options += [
                (f"list-reorder:{where}", lambda: list(reversed(node)) if prng.random() < 0.5 else _swap(node, index, other)),
                (f"list-duplicate:{where}[{index}]", lambda: [*node[: index + 1], _copy(node[index]), *node[index + 1 :]]),
                (f"list-remove:{where}[{index}]", lambda: [item for i, item in enumerate(node) if i != index]),
                (f"list-cardinality:{where}", lambda: [_copy(item) for item in node for _ in range(prng.choice([0, 3, 20]))]),
            ]
        else:
            options.append((f"list-cardinality:{where}", lambda: [None]))
    elif isinstance(node, dict):
        options += [
            (f"empty:{where}", lambda: {}),
            (f"object-unknown-key:{where}", lambda: {**_copy(node), "__unexpected": 1}),
            (f"object-nested:{where}", lambda: {**_copy(node), "nested": _copy(node)}),
        ]
        if node:
            key = prng.choice(sorted(node, key=str))
            options.append((f"object-nested:{where}.{key}", lambda: {**_copy(node), key: {"nested": _copy(node[key])}}))
    elif node is None:
        options += [(f"null-to-empty:{where}", lambda: ""), (f"null-to-zero:{where}", lambda: 0)]
    return options


def _swap(items: list[Any], a: int, b: int) -> list[Any]:
    out = [_copy(item) for item in items]
    out[a], out[b] = out[b], out[a]
    return out


def mutate(value: Any, prng: Prng, *, sequence_of_operations: bool = False) -> tuple[Any, str]:
    """One random mutation of one random site. The original is untouched."""

    sites = _sites(value)
    if sequence_of_operations and isinstance(value, list) and prng.random() < 0.5:
        path, node = sites[0]
    else:
        path, node = prng.choice(sites)
    if path and prng.random() < 0.12:
        return _delete(value, path), f"missing:{_text(path)}"
    options = _mutations_for(node, path, prng)
    description, produce = prng.choice(options)
    return _set(value, path, produce()), description


# --------------------------------------------------------------------------
# shrinking


def _local_shrinks(node: Any) -> Iterator[Any]:
    if isinstance(node, list):
        if node:
            yield []
        if len(node) > 1:
            half = len(node) // 2
            yield node[:half]
            yield node[half:]
        for index in range(len(node)):
            yield [item for i, item in enumerate(node) if i != index]
    elif isinstance(node, dict):
        if node:
            yield {}
        for key in sorted(node, key=str):
            yield {k: v for k, v in node.items() if k != key}
    elif isinstance(node, str):
        if node:
            yield ""
        if len(node) > 1:
            half = len(node) // 2
            yield node[:half]
            yield node[half:]
        if len(node) <= 64:
            for index in range(len(node)):
                yield node[:index] + node[index + 1 :]
    elif _is_number(node) and node != 0:
        yield 0 if isinstance(node, int) else 0.0
        if isinstance(node, float) and not math.isfinite(node):
            # nothing between a non-finite number and zero shrinks it
            return
        if isinstance(node, float) and node == int(node):
            yield int(node)
        magnitude = abs(node)
        delta = magnitude / 2 if isinstance(node, float) else magnitude // 2
        while delta >= (1e-9 if isinstance(node, float) else 1):
            yield node - delta if node > 0 else node + delta
            delta = delta / 2 if isinstance(node, float) else delta // 2


def _shrink_candidates(value: Any) -> Iterator[Any]:
    """Strictly smaller by JSON size, or a number strictly closer to zero.

    Every local shrink either removes structure or moves a number toward
    zero, so the sequence of accepted candidates is finite either way.
    """

    size = _size(value)
    for path, node in _sites(value):
        for smaller in _local_shrinks(node):
            candidate = _set(value, path, smaller)
            if _size(candidate) < size or (_is_number(node) and _is_number(smaller) and abs(smaller) < abs(node)):
                yield candidate


def shrink(value: Any, reproduces: Callable[[Any], bool], *, max_steps: int) -> tuple[Any, int]:
    """Greedy reduction. Every accepted step reproduced; the result is the last accepted."""

    current = _copy(value)
    steps = 0
    changed = True
    while changed and steps < max_steps:
        changed = False
        for candidate in _shrink_candidates(current):
            if steps >= max_steps:
                break
            steps += 1
            if reproduces(candidate):
                current = candidate
                changed = True
                break
    return current, steps


# --------------------------------------------------------------------------
# the search


@dataclass(frozen=True)
class SearchResult:
    status: str
    seed: int
    runs: int
    compared_runs: int
    unverifiable_runs: int
    shrink_runs: int
    elapsed_s: float
    corpus_size: int
    original: dict[str, Any] | None
    minimized: dict[str, Any] | None
    trace_digest: str
    reason: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "seed": self.seed,
            "runs": self.runs,
            "compared_runs": self.compared_runs,
            "unverifiable_runs": self.unverifiable_runs,
            "shrink_runs": self.shrink_runs,
            "elapsed_s": self.elapsed_s,
            "corpus_size": self.corpus_size,
            "original": dict(self.original) if self.original is not None else None,
            "minimized": dict(self.minimized) if self.minimized is not None else None,
            "trace_digest": self.trace_digest,
            "reason": self.reason,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SearchResult":
        return cls(
            status=data["status"],
            seed=int(data["seed"]),
            runs=int(data["runs"]),
            compared_runs=int(data["compared_runs"]),
            unverifiable_runs=int(data["unverifiable_runs"]),
            shrink_runs=int(data["shrink_runs"]),
            elapsed_s=float(data["elapsed_s"]),
            corpus_size=int(data["corpus_size"]),
            original=dict(data["original"]) if data.get("original") is not None else None,
            minimized=dict(data["minimized"]) if data.get("minimized") is not None else None,
            trace_digest=data["trace_digest"],
            reason=data.get("reason", ""),
        )


def _candidates(seeds: Sequence[CorpusItem], prng: Prng, sequence_of_operations: bool) -> Iterator[tuple[Any, str, str]]:
    """Candidates as ``(input, description, seed id)``; a candidate's state is its seed's."""

    for seed in seeds:
        yield _copy(seed.input), f"seed:{seed.id}", seed.id
    for tier in range(_TIERS):
        for seed in seeds:
            for candidate, description in _tier_candidates(seed.input, tier):
                yield candidate, description, seed.id
    bases: list[tuple[Any, str]] = [(seed.input, seed.id) for seed in seeds]
    generated: list[tuple[Any, str]] = []
    while True:
        base, origin = prng.choice(generated) if generated and prng.random() < 0.3 else prng.choice(bases)
        candidate, description = mutate(base, prng, sequence_of_operations=sequence_of_operations)
        generated.append((candidate, origin))
        if len(generated) > 64:
            del generated[0]
        yield candidate, description, origin


def search(
    seeds: Sequence[CorpusItem],
    evaluate: Callable[[CorpusItem], Any],
    *,
    seed: int,
    max_runs: int,
    max_seconds: float,
    shrink_steps: int,
    clock: Callable[[], float] = time.monotonic,
    sequence_of_operations: bool = False,
) -> SearchResult:
    """Run the search. ``evaluate`` returns anything with ``status`` and ``mandatory_equivalent``."""

    prng = Prng(seed)
    started = clock()
    runs = compared = unverifiable = shrink_runs = 0
    trace: list[Any] = []
    original: dict[str, Any] | None = None
    minimized: dict[str, Any] | None = None
    # the initial state (seeded files, seeded rows) is part of the input
    # domain, so every candidate runs under the state of the seed it came from
    states = {item.id: dict(item.initial_state) for item in seeds}
    if seeds and max_runs > 0:
        for candidate, description, origin in _candidates(seeds, prng, sequence_of_operations):
            if runs >= max_runs or clock() - started >= max_seconds:
                break
            runs += 1
            trace.append(candidate)
            state = states.get(origin, {})
            outcome = evaluate(CorpusItem(id=f"search-{runs}", input=candidate, initial_state=dict(state)))
            if outcome.status != "compared":
                unverifiable += 1
                continue
            compared += 1
            if outcome.mandatory_equivalent:
                continue
            original = {
                "id": f"search-{runs}",
                "input": candidate,
                "derived_from": origin,
                "mutation": description,
                "size": _size(candidate),
            }
            if state:
                original["initial_state"] = dict(state)
            digest = getattr(outcome, "digest", None)
            if callable(digest):
                original["comparison_digest"] = digest()
            counter = [0]

            def reproduces(value: Any) -> bool:
                counter[0] += 1
                result = evaluate(CorpusItem(id=f"shrink-{counter[0]}", input=value, initial_state=dict(state)))
                return result.status == "compared" and not result.mandatory_equivalent

            smallest, steps = shrink(candidate, reproduces, max_steps=shrink_steps)
            shrink_runs = counter[0]
            minimized = {"id": "minimized", "input": smallest, "shrink_steps": steps, "size": _size(smallest)}
            if state:
                minimized["initial_state"] = dict(state)
            break
    elapsed = clock() - started
    trace_digest = content_digest({"seed": seed, "trace": trace})
    if original is not None:
        status, reason = DIVERGED, f"divergence found on run {original['id']} and minimized in {minimized['shrink_steps'] if minimized else 0} step(s)"
    elif compared == 0:
        status, reason = UNVERIFIABLE, "no candidate could be compared" if runs else "the search budget allowed no runs"
    else:
        status, reason = NO_DIVERGENCE_FOUND, f"{compared} candidate(s) compared without divergence; this is not a proof"
    return SearchResult(
        status=status,
        seed=seed,
        runs=runs,
        compared_runs=compared,
        unverifiable_runs=unverifiable,
        shrink_runs=shrink_runs,
        elapsed_s=elapsed,
        corpus_size=len(seeds),
        original=original,
        minimized=minimized,
        trace_digest=trace_digest,
        reason=reason,
    )
